Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.

In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print("Vertical Stack: \n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Find common elements between A and B

In [5]:
common_elements = np.intersect1d(A, B)
print("common elements between A and B: ", common_elements)

common elements between A and B:  []

Extract all numbers from A which are within a specific range. eg
between 5 and 10

In [6]:
A = np.array([1, 3, 5, 7, 9, 11, 13])
#extract no.s between 5 and 10
result = A[(A >= 5) & (A <= 10)]
print("Numbers between 5 and 10:", result)

Numbers between 5 and 10: [5 7 9]

Filter the rows of iris_2d that has petallength (3rd column) > 1.5
and sepallength (1st column) < 5.0

In [12]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered rows - \n", filtered_iris)

Filtered rows -
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]

From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).

In [24]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,NaN,Front,...,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17.0,21.0,NaN,Front,...,7.0,187.0,115.0,72.0,38.0,34.0,NaN,3960.0,NaN,Volkswagen Eurovan
89,Volkswagen,Passat,Compact,17.6,20.0,22.4,21.0,30.0,NaN,Front,...,5.0,180.0,103.0,67.0,35.0,31.5,14.0,2985.0,non-USA,Volkswagen Passat
90,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18.0,25.0,NaN,Front,...,4.0,159.0,97.0,66.0,36.0,26.0,15.0,2810.0,non-USA,Volkswagen Corrado
91,Volvo,240,Compact,21.8,22.7,23.5,21.0,28.0,Driver only,Rear,...,5.0,190.0,104.0,67.0,37.0,29.5,14.0,2985.0,non-USA,Volvo 240
92,NaN,850,Midsize,24.8,26.7,28.5,20.0,28.0,Driver & Passenger,Front,...,5.0,184.0,105.0,69.0,38.0,30.0,15.0,3245.0,non-USA,Volvo 850

In [15]:
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

Replace missing values in Min.Price and Max.Price columns with
their respective mean.

In [20]:
#replacing nan to mean

df2 = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df2['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df2['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

print(df2[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091

<ipython-input-20-750007642e17>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-20-750007642e17>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

How to get the rows of a dataframe with row sum > 100?

In [22]:
#df with random integers
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

     0   1   2   3
0   35  30  24  37
1   34  17  22  15
2   10  30  20  26
3   36  37  30  19
4   24  34  19  12
5   28  36  13  37
6   32  14  19  32
7   32  13  14  32
8   33  28  39  28
9   29  32  22  30
10  16  33  31  26
11  12  33  35  30
12  37  23  14  29
13  39  11  36  34
14  13  19  32  14

In [23]:
#rows with sum >100
filtered_rows = df[df.sum(axis=1) > 100]
print(filtered_rows)

     0   1   2   3
0   35  30  24  37
3   36  37  30  19
5   28  36  13  37
8   33  28  39  28
9   29  32  22  30
10  16  33  31  26
11  12  33  35  30
12  37  23  14  29
13  39  11  36  34